### PR TITLE
Add print method and as.character for shiny.tag class

### PR DESCRIPTION
**Pull request by useless5771**
Added:
* as.character.shiny.tag calling out to htmltools::renderTags(x) and processing the dependencies
* print.shiny.tag the same as print.htmlwidget

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Interesting, I didn't realize it was the Shiny tag. This raises a few questions:

 1. does the functionality actually use Shiny, or is this just a convenience for getting at HTML formatting?
 2. we have a [package for Shiny compatibility](https://github.com/att/rcloud.shiny) but it doesn't use the S3 tags. maybe it should? instead it has an `rcloud.shinyApp` function which starts a server imperatively but if the tag launched our adapted shiny server, the special function wouldn't be needed.
 3. can Shiny interactivity be launched outside of `shinyApp`? I.e. does the use of the shiny S3 tag ever mean that a shiny server is expected?

**Comment by useless5771** [comment]
Regarding the first question, this solution doesn't use Shiny, it just uses htmltools to generate HTML and shiny.tag is defined in there: https://github.com/rstudio/htmltools/blob/master/R/tags.R. A bit misleading class name I guess...

I will have a look at the compatibility package and how RCloud deploys shinyApps, removing shiny server from the equation though would require RCloud to mimic somehow the http service that shinyapp starts up and that responds to UI requests...

**Comment by gordonwoodhull** [comment]
Okay, makes sense - I think htmltools was abstracted out of Shiny so that's probably why.

rcloud.shiny actually does run Shiny server as a subprocess of Rserve.

This requires changing the URL root so it can go through our server.

https://github.com/att/rcloud.shiny/blob/master/NEWS.md#new-architecture

But currently htmlwidgets does some transformations of the htmltools data before generating HTML, so that any dependencies go through shared.R instead of assuming an HTTP server. That explains the funny URLs you see in #6.

Previously we were embedding the dependencies using data URLs but that was slow.

I'm inclined to go ahead and merge this but I also want to work with you on a larger strategy here, so please spend a little time learning how this all fits together both on the RCloud side and the RStudio side.

**Comment by gordonwoodhull** [comment]
Awesome! Works great, code looks clean. Does not interfere with rcloud.shiny.

Thanks @useless5771!

**Pull request closed without merging**
